-- data_builder_tasks
-- Task-level source of truth for Data Builder.
-- mgmt-api owns task identity, lifecycle state, progress cache, cleanup orchestration, and telemetry.
-- exec-engine must not persist or mutate task truth directly.
-- manifest_json is the immutable or versioned task input snapshot.
-- runtime telemetry must not be written back into manifest_json.

CREATE TABLE IF NOT EXISTS `data_builder_tasks` (
  `task_id` CHAR(36) NOT NULL
    COMMENT 'UUID v4 task id; generated by mgmt-api in db_primary mode',

  `status` VARCHAR(32) NOT NULL DEFAULT 'PENDING'
    COMMENT 'PENDING|RUNNING|COMPLETED_OK|FAILED_ASSERTION|FAILED_EXECUTION',

  `manifest_json` JSON NOT NULL
    COMMENT 'manifest_v1 snapshot used by this task; runtime telemetry must not be written here',

  `manifest_hash` CHAR(64) NULL
    COMMENT 'Optional SHA-256 hex of normalized manifest_json for audit/dedupe',

  `manifest_version` VARCHAR(32) NOT NULL DEFAULT 'v1'
    COMMENT 'Manifest contract version, e.g. v1',

  `mysql_conn_snapshot_json` JSON NULL
    COMMENT 'Non-secret MySQL connection snapshot: host/port/user/database/options; password must not be stored here',

  `mysql_conn_encrypted_json` JSON NULL
    COMMENT 'Encrypted secret snapshot or encrypted password payload; never returned by public API',

  `mysql_conn_snapshot_version` VARCHAR(32) NOT NULL DEFAULT 'v1'
    COMMENT 'Connection snapshot encryption/serialization version',

  `execution_mode` VARCHAR(32) NOT NULL DEFAULT 'db_primary'
    COMMENT 'proxy|shadow|db_primary; steady-state default is db_primary, proxy/shadow are rollback modes',

  `orchestration_owner` VARCHAR(32) NOT NULL DEFAULT 'mgmt-api'
    COMMENT 'exec-engine|mgmt-api; steady-state default is mgmt-api in db_primary mode',

  `batch_count` INT NOT NULL DEFAULT 0
    COMMENT 'Denormalized count of expected batches derived from manifest batching',

  `completed_batches` INT NOT NULL DEFAULT 0
    COMMENT 'Denormalized count of terminal batches; source of detail is data_builder_task_batches',

  `current_batch_index` INT NULL
    COMMENT 'Current RUNNING batch index or most recently updated batch index',

  `rows_inserted_total` BIGINT NOT NULL DEFAULT 0
    COMMENT 'Denormalized sum of rows_inserted from data_builder_task_batches',

  `last_heartbeat_at` TIMESTAMP(3) NULL
    COMMENT 'Latest successful batch progress heartbeat observed by mgmt-api',

  `last_batch_started_at` TIMESTAMP(3) NULL
    COMMENT 'Set when mgmt-api transitions a batch to RUNNING and calls exec-engine',

  `row_map_flush_lag` INT NOT NULL DEFAULT 0
    COMMENT 'Estimated pending row-map flush count; cleanup may be blocked while > 0',

  `cleanup_status` VARCHAR(32) NOT NULL DEFAULT 'not_applicable'
    COMMENT 'not_applicable|eligible|running|completed|blocked',

  `cleanup_blocked_reason` VARCHAR(64) NULL
    COMMENT 'row_map_flush_lag|task_running|missing_cleanup_plan|partial_failure or null',

  `cleanup_started_at` TIMESTAMP(3) NULL
    COMMENT 'Set when cleanup transitions to running',

  `cleanup_completed_at` TIMESTAMP(3) NULL
    COMMENT 'Set when cleanup reaches completed',

  `cleanup_completed_by` VARCHAR(128) NULL
    COMMENT 'User id, username, or service account that confirmed cleanup',

  `last_error_json` JSON NULL
    COMMENT 'Task-level ErrorEnvelope; batch-specific errors live in data_builder_task_batches.last_error_json',

  `assertion_evaluated` BOOLEAN NOT NULL DEFAULT FALSE
    COMMENT 'Whether final task assertions have been evaluated',

  `assertion_runs_json` JSON NULL
    COMMENT 'Per-rule assertion results returned by exec-engine after final batch',

  `created_by` VARCHAR(128) NULL
    COMMENT 'User id, username, or service account that created the task',

  `created_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  `updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
    ON UPDATE CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`task_id`),
  KEY `idx_status_updated` (`status`, `updated_at`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_updated_at` (`updated_at`),
  KEY `idx_execution_mode` (`execution_mode`, `updated_at`),
  KEY `idx_cleanup_status` (`cleanup_status`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Data Builder: persistent task lifecycle and orchestration truth';
